- 3. Indexación y selección en arrays con Numpy
    
    En este ejercicio, trabajarás con arrays 1D y 2D en NumPy, aplicando indexación y selección de elementos.
    
    ### Tareas:
    
    1. **Creación de arrays**
        - Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
        - Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
    2. **Indexación en arrays**
        - Extrae y muestra:
            - El primer y último elemento del array 1D.
            - El primer elemento de la primera fila del array 2D.
            - El último elemento de la última fila del array 2D.
            - El elemento ubicado en la segunda fila y tercera columna del array 2D.
    3. **Selección de filas y columnas**
        - Extrae y muestra:
            - La primera fila completa del array 2D.
            - La segunda columna completa del array 2D.

In [18]:
import numpy as np

print("1. **Creación de arrays**")

array_1d = np.arange(1,11)
print("Array 1D : ", array_1d)
array_2d = np.arange(1,10).reshape(3, 3)
print ("Array 2D : \n", array_2d)

print("***************************************\n")
print("2. **Indexación en arrays**")

print ("Primer elemento del array 1d : ", array_1d[0])
print ("Último elemento del array 1d : ", array_1d[-1])
print ("El primer elemento de la primera fila del array 2D. :",array_2d[0,0])
print ("El último elemento de la última fila del array 2D. :",array_2d[-1,-1])
print ("El elemento ubicado en la segunda fila y tercera columna del array 2D. :",array_2d[1,2])

print("***************************************\n")
print("3. **Selección de filas y columnas**")

print ("La primera fila completa del array 2D. :" ,array_2d[0])#Es lo mismo que poner ,array_2d[0,:]
print ("La segunda columna completa del array 2D. :",array_2d[:,1])


1. **Creación de arrays**
Array 1D :  [ 1  2  3  4  5  6  7  8  9 10]
Array 2D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
***************************************

2. **Indexación en arrays**
Primer elemento del array 1d :  1
Último elemento del array 1d :  10
El primer elemento de la primera fila del array 2D. : 1
El último elemento de la última fila del array 2D. : 9
El elemento ubicado en la segunda fila y tercera columna del array 2D. : 6
***************************************

3. **Selección de filas y columnas**
La primera fila completa del array 2D. : [1 2 3]
La segunda columna completa del array 2D. : [2 5 8]


- 4. Explorando una imagen en formato de Array 3D
    
    En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.
    
    ### Tareas:
    
    1. **Creación del array 3D**
        - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
        - Usa `np.random.randint()` para generar valores enteros.
    2. **Indexación en el array 3D**
        - Extrae y muestra:
            - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
            - El último píxel de la imagen (posición `[-1,-1]`).
            - El valor del canal rojo del píxel en la segunda fila y tercera columna.
    3. **Slicing en el array 3D**
        - Extrae y muestra:
            - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
            - Solo los valores del canal azul para todos los píxeles de la imagen.
            - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).

In [33]:
print (" 1. **Creación del array 3D**")

array_3D = np.random.randint(0, 255, size=(4,4,3))
print(array_3D)

print("***************************************\n")
print(" 2. **Indexación en el array 3D**")

print ("Valores RGB del primer pixel :",array_3D[0,0,:])#También se podría poner esto ,array_3D[0,0]
print ("Valores RGB del último pixel :",array_3D[-1,-1])#,array_3D[-1,-1,:]
print ("El valor del canal rojo del píxel en la segunda fila y tercera columna. ",array_3D[1,2,0])

print("***************************************\n")
print(" 3. **Slicing en el array 3D**")

print ("Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB). : \n ", array_3D[0,:,:])
print ("Solo los valores del canal azul para todos los píxeles de la imagen. : \n ", array_3D[:,:,2])#También array_3D[:,:,-1]
print ("Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición [1:3, 1:3, :]). : \n" , array_3D[1:3,2:3,:])

 1. **Creación del array 3D**
[[[ 26 199 221]
  [ 69 237 121]
  [154  60 205]
  [ 32 244 169]]

 [[148  64 147]
  [ 34 177 173]
  [ 12 136  32]
  [ 85 251  96]]

 [[ 93 206 213]
  [119 243  68]
  [197 129  87]
  [108 201 230]]

 [[246 170 144]
  [ 14 237 178]
  [245 106 199]
  [ 93 205 101]]]
***************************************

 2. **Indexación en el array 3D**
Valores RGB del primer pixel : [ 26 199 221]
Valores RGB del último pixel : [ 93 205 101]
El valor del canal rojo del píxel en la segunda fila y tercera columna.  12
***************************************

 3. **Slicing en el array 3D**
Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB). : 
  [[ 26 199 221]
 [ 69 237 121]
 [154  60 205]
 [ 32 244 169]]
Solo los valores del canal azul para todos los píxeles de la imagen. : 
  [[221 121 205 169]
 [147 173  32  96]
 [213  68  87 230]
 [144 178 199 101]]
Un recorte central de la imagen, seleccionando las filas y columnas inte

- 5. Distancia euclidiana con fórmula optimizada
    
    Calcular la distancia euclidiana entre dos puntos en un espacio de 5 dimensiones.
    
    ### Tareas:
    
    - Crea dos puntos en un espacio de 5 dimensiones como arrays de NumPy. Los puntos serán:
        - **Punto 1**: (2,3,5,7,11)
            
            (2,3,5,7,11)
            
        - **Punto 2**: (1,4,6,8,10)
            
            (1,4,6,8,10)
            
    - Utiliza la función `np.linalg.norm()` para calcular la distancia entre estos dos puntos en 5 dimensiones.
    - Imprime el resultado de la distancia.

In [4]:
import numpy as np

punto1 = np.array([2,3,5,7,11])
punto2 = np.array([4,5,6,7,8])

distancia =np.linalg.norm(punto1-punto2)
print("Esta es la distancia entre estos dos puntos : ", distancia)

Esta es la distancia entre estos dos puntos :  4.242640687119285


- 6. Análisis del rendimiento académico utilizando normas L1 y L2
    
    Eres un analista educativo y debes evaluar el rendimiento de un grupo de estudiantes en varias asignaturas. Dispones de una matriz con las calificaciones obtenidas por cada estudiante en distintas materias. Para analizar los datos, se te pide:
    
    ### Tareas:
    
    - **Calcular la norma L1 y la norma L2** de las calificaciones de cada estudiante para medir la dispersión y la magnitud de sus puntuaciones.
    - **Calcular la norma L1 y la norma L2** para cada asignatura para entender lo variadas que son las calificaciones en cada materia.
    - **Utilizar `axis=1`** para obtener las puntuaciones totales de cada estudiante (sumando todas las asignaturas).
    - **Utilizar `axis=0`** para obtener las puntuaciones totales de cada asignatura (sumando las calificaciones de todos los alumnos).
    - **Aplicar `keepdims=True`** para mantener la estructura de la matriz al realizar las operaciones y evitar problemas de dimensión.
        
        ```python
        #Datos de entrada
        calificaciones = np.array([
            [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
            [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
            [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
            [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
            [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
            [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
            [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
            [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
            [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
            [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
            [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
            [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
            [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
            [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
            [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
            [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
            [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
            [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
            [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
            [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
            [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
            [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
            [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
            [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
            [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
            [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
            [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
            [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
            [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
            [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
            [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
            [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
            [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
            [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
            [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
            [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
            [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
            [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
            [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
            [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
            [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
            [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
            [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
            [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
            [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
            [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
            [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
            [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
            [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
        ])
        
        ```
        
        ### Preguntas:
        
        - ¿Por qué la norma L1 representa la suma absoluta de las calificaciones?
        - ¿Por qué la norma L2 nos da una idea de la magnitud total de los valores, penalizando más las notas altas?
        - ¿Cómo afecta `keepdims=True` en las operaciones realizadas?

In [1]:
import numpy as np



#Datos de entrada
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])
contador = 0

norma_L2_alumnos =[np.linalg.norm(alumno) for alumno in calificaciones ]

for alumno in norma_L2_alumnos :
    print("Alumno",contador,":\n",norma_L2_alumnos[contador])
    contador+=1

for i in range(10):
    nuevo_array = calificaciones[:,i]
    norma_L2_asignaturas =[np.linalg.norm(nuevo_array) for asignatura in nuevo_array ]
    print ("Asignatura",i,":\n",norma_L2_asignaturas)

print("*************************************************************************")
print("*************************************************************************")

print ("Asignatura",np.linalg.norm(calificaciones ,axis=0))
print ("Alumnos ",np.linalg.norm(calificaciones ,axis=1))


Alumno 0 :
 235.98516902551313
Alumno 1 :
 231.7930111112067
Alumno 2 :
 246.02032436365903
Alumno 3 :
 243.73756378531397
Alumno 4 :
 227.02643017939565
Alumno 5 :
 247.06679258856298
Alumno 6 :
 226.0862667213557
Alumno 7 :
 242.81474419812318
Alumno 8 :
 246.2782978664584
Alumno 9 :
 244.45040396775784
Alumno 10 :
 246.81166909204273
Alumno 11 :
 250.0959815750745
Alumno 12 :
 238.03991261971174
Alumno 13 :
 226.03981950090122
Alumno 14 :
 244.64055264816582
Alumno 15 :
 244.44426767670376
Alumno 16 :
 235.94490882407274
Alumno 17 :
 247.0344105585293
Alumno 18 :
 236.8818270783979
Alumno 19 :
 256.18547968220213
Alumno 20 :
 247.7216179504728
Alumno 21 :
 254.58593833909995
Alumno 22 :
 242.72412323458911
Alumno 23 :
 249.4554068365727
Alumno 24 :
 247.9576576756604
Alumno 25 :
 223.5799633240868
Alumno 26 :
 253.42454498331452
Alumno 27 :
 233.13515393436487
Alumno 28 :
 245.56261930513773
Alumno 29 :
 249.85595850409493
Alumno 30 :
 247.4510052515447
Alumno 31 :
 240.723908243448

- 7. Producto cruzado para calcular variaciones en la ruta de un avión
    
    **Contexto:**
    
    Una compañía aérea está analizando la trayectoria de sus aviones para garantizar que mantienen el rumbo adecuado. En particular, necesitan calcular la dirección perpendicular a la ruta de vuelo cuando hay desviaciones debido a corrientes de aire. Para ello, utilizarán el **producto cruzado** de dos vectores:
    
    1. **Vector de vuelo previsto:** Representa la trayectoria que el avión debería seguir.
    2. **Vector de vuelo real:** Representa la trayectoria que el avión está siguiendo en realidad.
    
    El producto cruzado entre estos dos vectores proporciona un tercer vector que indica la dirección de la desviación en el espacio tridimensional.
    
    ---
    
    ### **Enunciado del Ejercicio**
    
    Dado un avión que vuela en el espacio tridimensional, representaremos su trayectoria mediante vectores en un sistema de coordenadas cartesianas.
    
    1. Define los siguientes vectores en NumPy:
        - **Vector de vuelo previsto**: `v1 = [3, 4, 0]`
        - **Vector de vuelo real**: `v2 = [4, 3, 1]`
    2. Calcula el **producto cruzado** entre `v1` y `v2` utilizando NumPy.
    3. Interpreta el resultado:
        - ¿En qué dirección ocurre la desviación?
        - ¿Cómo se podría corregir la trayectoria del avión basándonos en este cálculo?
    
    ---
    
    ### **Explicación**
    
    - El producto cruzado entre dos vectores en el espacio tridimensional genera un tercer vector **perpendicular** al plano que forman los dos vectores originales.
    - En este caso, el vector resultante indica la dirección en la que el avión está siendo desviado.
    - Si el resultado es `[x, y, z]`, la desviación se produce en la dirección del eje **z**, lo que significa que el avión está cambiando de altitud en lugar de mantenerse en el plano original.
    
    **Desafío Extra:**
    
    - Modifica el vector `v2` y observa cómo cambia la desviación.
    - ¿Cómo cambiaría el resultado si el avión volara completamente en un plano 2D (sin componente en `z`)?

In [12]:
import numpy as np

vector_vuelo_previsto = [3, 4, 0]
vector_vuelo_real = [4, 3, 1]

desviacion = np.cross(vector_vuelo_previsto,vector_vuelo_real)
print("La desviación es de :",desviacion)

La desviación es de : [ 4 -3 -7]


- 8. Análisis del rendimiento de un atleta con producto escalar
    
    ### **Contexto**
    
    Eres un entrenador de atletismo y necesitas evaluar el desempeño de un atleta en diferentes pruebas de velocidad y resistencia. Para hacerlo, utilizas dos vectores:
    
    - **Vector de rendimiento del atleta:** Contiene los tiempos que ha tardado en recorrer diferentes distancias (100m, 200m, 400m, 800m, 1500m).
    - **Vector de importancia de cada prueba:** Define qué tan importante es cada distancia en la evaluación final (por ejemplo, si priorizas pruebas de velocidad o de resistencia).
    
    El **producto escalar** te permitirá calcular un **índice de rendimiento** que refleja la eficiencia del atleta considerando la importancia de cada prueba.
    
    ### **Objetivos del ejercicio**
    
    1. Representar el rendimiento de un atleta y la importancia de cada prueba como vectores.
    2. Calcular el producto escalar entre ambos vectores.
    3. Interpretar el resultado: un menor valor indica mejor rendimiento, ya que los tiempos son menores en pruebas más importantes.
    
    ### **Datos de entrada**
    
    Supongamos que tenemos los siguientes datos:
    
    - **Tiempos del atleta (en segundos):** `[11, 22, 50, 110, 250]`
    - **Importancia de las pruebas:** `[0.4, 0.3, 0.2, 0.1, 0.05]` *(priorizamos más las pruebas cortas de velocidad que las largas de resistencia).*
    
    ### **Tareas**
    
    1. Representa los datos como vectores en NumPy.
    2. Calcula el producto escalar entre los vectores.
    3. Explica qué significa el resultado obtenido en términos del rendimiento del atleta.
    
    ### Preguntas
    
    - ¿Cómo afectaría al resultado si el atleta mejora su tiempo en la prueba de 100m?
    - ¿Qué pasaría si le damos más importancia a las pruebas de resistencia?
    - ¿Cómo se podría utilizar esta métrica para comparar a diferentes atletas?

In [19]:

tiempos_del_atleta1 = np.array([11, 22, 50, 110, 250])
tiempos_del_atleta2 =  np.array([10, 20, 50, 110, 250])

importancia_de_la_prueba = [0.4, 0.3, 0.2, 0.1, 0.05]

rendimiento_por_prueba = np.dot(tiempos_del_atleta1,importancia_de_la_prueba)
rendimiento_por_prueba1 = np.dot(tiempos_del_atleta2,importancia_de_la_prueba)

print("Este es el rendimiento del atleta1",rendimiento_por_prueba)

print("Este es el rendimiento del atleta2",rendimiento_por_prueba1)


Este es el rendimiento del atleta1 44.5
Este es el rendimiento del atleta2 43.5


- 9. Normalización de datos con la norma L2 en rendimiento deportivo
    
    ### **Contexto**
    
    Eres un analista de rendimiento deportivo y tienes un equipo de **fútbol** que ha jugado **una temporada completa**. Para evaluar a cada jugador, has recopilado sus estadísticas en diferentes categorías:
    
    - **Goles marcados**
    - **Asistencias**
    - **Pases completados**
    - **Regates exitosos**
    - **Tiros a puerta**
    
    Sin embargo, los valores en cada categoría tienen escalas diferentes, por lo que es difícil comparar directamente el desempeño de los jugadores. Para resolver este problema, aplicarás la **normalización con la norma L2**, lo que permitirá convertir todas las estadísticas a una escala comparable.
    
    ### **Objetivo del ejercicio**
    
    1. Representar el rendimiento de los jugadores como una matriz en NumPy.
    2. Aplicar la **normalización L2** a cada jugador para escalar sus valores entre 0 y 1 mientras se mantiene la proporción relativa.
    3. Comparar los jugadores después de la normalización.
    
    ### **Datos de entrada**
    
    Supongamos que tenemos los datos de 5 jugadores:
    
    | Jugador | Goles | Asistencias | Pases | Regates | Tiros a puerta |
    | --- | --- | --- | --- | --- | --- |
    | Jugador 1 | 10 | 7 | 300 | 25 | 40 |
    | Jugador 2 | 15 | 10 | 250 | 30 | 50 |
    | Jugador 3 | 5 | 12 | 280 | 20 | 35 |
    | Jugador 4 | 8 | 6 | 310 | 15 | 38 |
    | Jugador 5 | 12 | 9 | 270 | 28 | 45 |
    
    Cada jugador es un **vector** con 5 componentes. Aplicaremos la **norma L2** para normalizar sus estadísticas.
    
    ### **Tareas**
    
    1. Representar los datos como una matriz en NumPy.
    2. Aplicar la normalización L2 a cada jugador (por filas, usando `axis=1`).
    3. Mostrar los valores normalizados y analizar cómo se comparan los jugadores tras la normalización.
    
    ### Preguntas
    
    - ¿Cómo cambian los valores después de la normalización?
    - ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
    - ¿Qué pasaría si normalizamos por **columnas (axis=0)** en lugar de por filas?

In [23]:
import numpy as np

jugadores = np.array([
    [10,7,300, 25 ,40],
    [15,10,250,30 ,50],
    [5,12,280,20 ,35],
    [8,6,310,15 ,38],
    [12,9,270,28 ,45],
])

norma_L2_jugadores =np.linalg.norm(jugadores ,axis=0) 
norma_L2_estadisticas =np.linalg.norm(jugadores ,axis=1) 

print ("Norma L2 en jugadores sin normalizar datos : \n",norma_L2_jugadores)
print ("Norma L2 en estadisticas sin normalizar datos : \n",norma_L2_estadisticas)

print ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n")
normalizacion_jugadores = jugadores / np.linalg.norm(jugadores)
print ("Esto es la matriz normalizada \n ",normalizacion_jugadores)

print ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ \n")

norma_L2_jugadores_normalizada = np.linalg.norm(normalizacion_jugadores ,axis=0)
norma_L2_estadisticas_normalizada = np.linalg.norm(normalizacion_jugadores ,axis=1)

print ("Norma L2 en jugadores  normalizados : \n",norma_L2_jugadores_normalizada)
print ("Norma L2 en estadisticas  normalizadas  : \n",norma_L2_estadisticas_normalizada)

Norma L2 en jugadores sin normalizar datos : 
 [ 23.62202362  20.24845673 632.37647015  54.16641026  93.77632964]
Norma L2 en estadisticas sin normalizar datos : 
 [303.9309132  257.34218465 283.1854516  312.84021481 275.56124546]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

Esto es la matriz normalizada 
  [[0.01556817 0.01089772 0.46704502 0.03892042 0.06227267]
 [0.02335225 0.01556817 0.38920419 0.0467045  0.07784084]
 [0.00778408 0.0186818  0.43590869 0.03113633 0.05448859]
 [0.01245453 0.0093409  0.48261319 0.02335225 0.05915904]
 [0.0186818  0.01401135 0.42034052 0.04359087 0.07005675]]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

Norma L2 en jugadores  normalizados : 
 [0.03677516 0.03152314 0.98449428 0.08432717 0.14599256]
Norma L2 en estadisticas  normalizadas  : 
 [0.47316473 0.400634

- 10. Hablando de pilotos de carreras
    
    ### **Contexto:**
    
    Eres un ingeniero de datos en un equipo de Fórmula 1 y debes analizar el rendimiento de **10 pilotos** en **5 carreras**. Para ello, trabajarás con matrices en NumPy para transformar los datos y extraer información útil.
    
    ### **Tareas:**
    
    1. **Representar los datos** en un array bidimensional de NumPy donde cada fila sea un piloto y cada columna una carrera.
    2. **Transformación de arrays:**
        - Reorganiza la matriz con `.reshape()` para analizar los datos de otra manera.
        - Usa `.ravel()` o `.flatten()` para convertir la matriz en un array 1D.
    3. **Operaciones aritméticas:**
        - Calcula el promedio de posiciones por piloto y por carrera (`axis=0` y `axis=1`).
        - Aplica una penalización sumando un valor a cada posición y recalculando los valores.
    4. **Producto escalar:**
        - Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el **producto escalar**.
    5. **Producto cruzado:**
        - Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su **producto cruzado**, interpretando el resultado en términos de diferencias de rendimiento.
    6. **Extra bonus:**
        - Normaliza los datos usando la **norma L2** (`np.linalg.norm()`) para comparar el rendimiento de los pilotos en diferentes circuito

In [15]:
import numpy as np

print ("\n")

print ("***********************************************************\n")
print ("Representar los datos:")

array_pilotos = np.array([
    [1, 2, 3, 4, 5], 
    [2, 3, 4, 5, 6], 
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8], 
    [5, 6, 7, 8, 9], 
    [6, 7, 8, 9, 10], 
    [7, 8, 9, 10, 1], 
    [8, 9, 10, 1, 2],
    [9, 10, 1, 2, 3], 
    [10, 1, 2, 3, 4]  
])
print (array_pilotos)  
print ("\n")

print ("***********************************************************\n")
print ("Transformación de arrays::")

array_pilotos2 = array_pilotos.reshape(5,10)
print (array_pilotos2)

flattened = array_pilotos.ravel() 
print("Array aplanado:", flattened)

print ("\n")

print ("***********************************************************\n")
print ("Operaciones aritméticas:")

promedio_piloto = array_pilotos.mean(axis=1)
print("\nPromedio de posiciones por piloto:",promedio_piloto)


promedio_carrera = array_pilotos.mean(axis=0)
print("\nPromedio de posiciones por carrera:",promedio_carrera)




array_penalizacion = array_pilotos+1
print("Array de penalización: \n", array_penalizacion)

promedio_piloto_penalizado = array_penalizacion.mean(axis=1)
promedio_carrera_penalizado = array_pilotos.mean(axis=0)
print("\nPromedio de posiciones por carrera:",promedio_carrera)
print("\nRendimiento penalizado:",array_penalizacion)
print("\nPromedio penalizado por piloto:",promedio_piloto_penalizado)
print("\nPromedio penalizado por carrera:",promedio_carrera_penalizado)



print ("***********************************************************\n")
print ("Producto escalar")

piloto_1 = array_pilotos[0]
piloto_2 = array_pilotos[1]
producto_escalar = np.dot(piloto_1, piloto_2)
print("Producto escalar entre pilotos 1 y 2: ", producto_escalar)


print ("***********************************************************\n") 
print ("Produccto cruzado :")

piloto_1 = piloto_1[:3]
piloto_2 = piloto_2[:3]

producto_cruzado = np.cross(piloto_1, piloto_2)
print("Producto cruzado entre pilotos 1 y 2: ", producto_cruzado)

print ("***********************************************************\n")
print("Extra bonus ")

array_pilotos_normalizado =array_pilotos/np.linalg.norm(array_pilotos)

promedio_piloto =np.linalg.norm(array_pilotos_normalizado,axis=1)
print("Promedio de pilotos:", promedio_piloto)





***********************************************************

Representar los datos:
[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10  1]
 [ 8  9 10  1  2]
 [ 9 10  1  2  3]
 [10  1  2  3  4]]


***********************************************************

Transformación de arrays::
[[ 1  2  3  4  5  2  3  4  5  6]
 [ 3  4  5  6  7  4  5  6  7  8]
 [ 5  6  7  8  9  6  7  8  9 10]
 [ 7  8  9 10  1  8  9 10  1  2]
 [ 9 10  1  2  3 10  1  2  3  4]]
Array aplanado: [ 1  2  3  4  5  2  3  4  5  6  3  4  5  6  7  4  5  6  7  8  5  6  7  8
  9  6  7  8  9 10  7  8  9 10  1  8  9 10  1  2  9 10  1  2  3 10  1  2
  3  4]


***********************************************************

Operaciones aritméticas:

Promedio de posiciones por piloto: [3. 4. 5. 6. 7. 8. 7. 6. 5. 4.]

Promedio de posiciones por carrera: [5.5 5.5 5.5 5.5 5.5]
Array de penalización: 
 [[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8

In [ ]:
#supongamos que tenemos un conjunto de datos de discos de música con el siguiente formato: [número de canciones, premios grammy, ventas en miles de euros].
#  Cada disco es un vector en un espacio tridimensional. 
# Dado un nuevo disco de nuestra discográfica queremos evaluar qué disco existente es más similar en términos de distancia euclidiana.
disco_1 = np.array([70, 2, 150])  
disco_2 = np.array([85, 3, 200])  
disco_3 = np.array([120, 4, 300]) 
disco_4 = np.array([60, 2, 130]) 

disco_nuevo = np.array([80, 3, 180])

discos=np.array([disco_1,disco_2,disco_3,disco_4])

#distancia =np.linalg.norm(punto1-punto2)

def distancia_euclidiana(d1, d2):
    return np.sqrt(np.sum((d1 - d2) ** 2))

distancias = [distancia_euclidiana(disco_nuevo, disco) for disco in discos]

indice_disco_mas_parecido = np.argmin(distancias) 
disco_disco_mas_parecido = discos[indice_disco_mas_parecido]
print("El disco más parecido es: ", disco_disco_mas_parecido ,"con una distancia de ",indice_disco_mas_parecido)